apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterlab
  namespace: dotfiles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyter-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jupyterlab
  namespace: dotfiles
