include: .gitlab/ci-job-templates.yml

stages:
  - build

kaniko build:
  extends: .kaniko build
  variables:
    name: gcloud-slim
    dockerfile: .docker/${name}
    image: ${CI_REGISTRY_IMAGE}/${name}
  only:
    refs:
      - gcloud-slim
