stages:
  - build
  - deploy

build jupyterlab:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh .kaniko-build.sh .jupyterlab.Dockerfile ${CI_REGISTRY_IMAGE}/jupyterlab
  only:
    refs:
      - build
      - build-jupyterlab

build gitpod:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh .kaniko-build.sh .gitpod.Dockerfile ${CI_REGISTRY_IMAGE}/gitpod
  only:
    refs:
      - build
      - build-gitpod

build theia:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh .kaniko-build.sh .theia.Dockerfile ${CI_REGISTRY_IMAGE}/theia
  only:
    refs:
      - build
      - build-theia

build focal:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh .kaniko-build.sh .focal.Dockerfile ${CI_REGISTRY_IMAGE}/focal
  only:
    refs:
      - build
      - build-focal
