stages:
  - build
  - deploy

build-jupyterlab:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - bash .kaniko-build.sh
  only:
    refs:
      - build

build-gitpod:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - bash .kaniko-build.sh .gitpod.Dockerfile ${CI_REGISTRY_IMAGE}/gitpod
  only:
    refs:
      - build
