include: .gitlab/ci-job-templates.yml

stages:
  - build

build jupyterlab:
  extends: .kaniko build
  variables:
    dockerfile: .docker/llamastack-local-cpu
    image: ${CI_REGISTRY_IMAGE}/llamastack-local-cpu
  only:
    refs:
      - dockerfiles
