include: .gitlab/ci-job-templates.yml

stages:
  - build

kaniko build:
  extends: .kaniko build
  variables:
    name: llamastack-local-gpu
    dockerfile: .docker/${name}
    image: ${CI_REGISTRY_IMAGE}/${name}
  only:
    refs:
      - dockerfiles
