include: .gitlab/ci-job-templates.yml

stages:
  - build

build jupyterlab:
  extends: .kaniko build
  variables:
    dockerfile: .jupyterlab.Dockerfile
    image: ${CI_REGISTRY_IMAGE}/jupyterlab
  only:
    refs:
      - build-all
      - build-jupyterlab

build gitpod:
  extends: .kaniko build
  variables:
    dockerfile: .gitpod.Dockerfile
    image: ${CI_REGISTRY_IMAGE}/gitpod
  only:
    refs:
      - build-all
      - build-gitpod

build theia:
  extends: .kaniko build
  variables:
    dockerfile: .theia.Dockerfile
    image: ${CI_REGISTRY_IMAGE}/theia
  only:
    refs:
      - build-all
      - build-theia

build focal:
  extends: .kaniko build
  variables:
    dockerfile: .focal.Dockerfile
    image: ${CI_REGISTRY_IMAGE}/focal
  only:
    refs:
      - build-all
      - build-focal

build bullseye:
  extends: .kaniko build
  variables:
    dockerfile: .bullseye.Dockerfile
    image: ${CI_REGISTRY_IMAGE}/bullseye
  only:
    refs:
      - build-all
      - build-bullseye
