#!/bin/sh
dotfiles=".ackrc .bashrc .gitconfig .hgrc .profile .spacemacs .synergy.conf .tmux.conf .vimrc"
cd $HOME
for f in $dotfiles; do
    ln -sf dotfiles/$f;
done;

if [[ "$(which emacs)" && ! -e ~/.emacs.d ]]; then
    git clone -b develop --depth 1 --recursive https://github.com/syl20bnr/spacemacs ~/.emacs.d
fi

if [ "$(which vim)" ]; then
    mkdir -p ~/.vim/bundle
    cd ~/.vim/bundle
    if [ ! -e vundle ]; then
        git clone https://github.com/gmarik/vundle.git
    fi
    #vim +BundleInstall +qall &>/dev/null
fi
