#!/bin/sh
dotfiles=".ackrc .bash_aliases .bashrc .gitconfig .hgrc .profile .synergy.conf .tmux.conf .vimrc"
cd $HOME
for f in $dotfiles; do
    ln -sf dotfiles/$f;
done;
# the command below will sometime lock up during automated deployments
#vim +BundleInstall +qall &>/dev/null
