#!/bin/bash
dotfiles=".ackrc .bashrc .gitconfig .hgrc .histories .profile .spacemacs .synergy.conf .tmux.conf .vimrc .wezterm.lua .xonshrc"
cd $HOME
for f in $dotfiles; do
    ln -sf dotfiles/$f;
done;
ln -sf dotfiles/.tmux.conf .tmate.conf

if [[ "$(uname)" == "Darwin" ]]; then
    mkdir -p ~/.hammerspoon
    ln -sf ~/dotfiles/.hammerspoon/init.lua ~/.hammerspoon/init.lua
    nushell_dir="${HOME}/Library/Application Support/nushell"
else
    nushell_dir="${HOME}/.config/nushell"
fi

mkdir -p "${nushell_dir}"
for f in {config,env}.nu; do
    ln -sf ~/dotfiles/.config/nushell/$f "${nushell_dir}/$f"
done

if [[ "$(which emacs)" && ! -e ~/.emacs.d ]]; then
    git clone -b develop --depth 1 --recursive https://github.com/syl20bnr/spacemacs ~/.emacs.d
fi

nvim=$(which nvim)
if [[ -n "${nvim?=$(which vim)}" ]]; then
    mkdir -p ~/.vim/bundle
    cd ~/.vim/bundle
    if [ ! -e vundle ]; then
        git clone --depth 1 https://github.com/gmarik/vundle.git
    fi
    #vim +BundleInstall +qall &>/dev/null
    if [[ -n "${nvim}" ]]; then
        mkdir -p ~/.config/nvim
        ln -sf ~/dotfiles/.config/nvim/init.vim ~/.config/nvim/init.vim
        ${nvim} --headless +BundleInstall +qall
    fi
fi

mkdir -p ~/.config/ghostty
ln -sf ~/dotfiles/.config/ghostty/config ~/.config/ghostty/config
