#!/bin/bash

apt-update () {
    if [[ -z "apt_updated" ]]; then
        sudo apt update && export apt_updated=1
    fi
}

install-cargo () {
    #curl https://sh.rustup.rs -sSf | sh
    apt-update && sudo apt install -y cargo;
}

install-bat() {
    cargo install bat || \
        install-cargo && \
    cargo install bat ;
}

yat() {
    bat --language=yaml --style=plain "$@" || \
        install-bat && \
    bat --language=yaml --style=plain "$@" ;
}
