#!/bin/bash

cert-sig-alg() {
  echo | openssl s_client -connect $1:443 $2 2>/dev/null | openssl x509 -text | grep 'Signature Algorithm' | uniq;
}

cert-dates() {
  echo | openssl s_client -connect www.allizom.org:443 2>/dev/null | openssl x509 -noout -dates;
}