#!/bin/bash

rsshtun() {
    REMOTE_PORT="${2:-2222}"
    autossh -R $REMOTE_PORT:localhost:22 $1 "
        while true;
           do nc -zv localhost $REMOTE_PORT;
           sleep 2;
        done"; }
rsshtunair() {
    REMOTE_PORT="${2:-2224}"
    BASTION="${1:-ssh.us-west.moz.works}"
    while true; do
    ssh -R $REMOTE_PORT:localhost:22 $BASTION \
        "while true; do nc -zv localhost $REMOTE_PORT; sleep 2; done";
    done; }