#!/bin/bash

rsshtun() {
    BASTION="${1:-ssh.us-west.moz.works}"
    REMOTE_PORT="${2:-2222}"
    autossh -R $REMOTE_PORT:localhost:22 $BASTION "
        while true;
           do nc -zv localhost $REMOTE_PORT;
           sleep 2;
        done";
}

rsshtun-aspire() {
    BASTION="${1:-ssh.us-west.moz.works}"
    REMOTE_PORT="${2:-2223}"
    rsshtun ${BASTION} ${REMOTE_PORT}
}

rsshtun-air() {
    BASTION="${1:-ssh.us-west.moz.works}"
    REMOTE_PORT="${2:-2224}"
    #autossh installed on air does not supprt port forwarding
    while true; do
        ssh -R $REMOTE_PORT:localhost:22 $BASTION \
        "while true; do nc -zv localhost $REMOTE_PORT; sleep 2; done";
    done;
}
