#!/bin/bash

# copied from https://github.com/metadave/sts-helper#paste-this-function-into-your-bashrc
function sts_assume() {
    echo set AWS_PROFILE
    echo unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
    read -p "Helper profile: " prof
    read -p "MFA token: " token
    eval $(sts-helper assume-role --helper-profile $prof --token $token)
}
