#!/bin/bash

synair() {
    ssh -R 24800:localhost:24800 ${1:-air.local} 'killall synergyc; sleep 1; /Applications/syn.app/Contents/MacOS/synergyc -f -n air localhost'
}

synmbp() {
    ssh -R 24800:localhost:24800 ${1:-mbp13.local} 'killall synergyc; sleep 1; /Applications/Synergy.app/Contents/MacOS/synergyc -f localhost'
}

synx250() {
    ssh -R 24800:localhost:24800 ${1:-x250.local} 'killall synergyc; sleep 1; DISPLAY=:0 synergyc -f localhost'
}
